src: /home/fargus/Pictures/
dest: /tmp/SortWallpaper/
exclude:
  - excludeme
verbose: false
params:
  Desktop:
    min_width: 1400
    min_height: 800
    min_ratio: 1.3
    max_ratio: 1.9
  Phone:
    min_width: 720
    min_height: 1500
    min_ratio: 0.36
    max_ratio: 0.76
filetypes:
  - png
  - jpg
  - JPG
  - JPEG
  - PNG
